---
name: Gerrit Publish to test.pypi.org

on:
  push:
    tags:
      - 'beta.v.[0-9]+.[0-9]+.[0-9]+'


jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref  }}
          submodules: "true"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -U packaging
          pip install twine build

      - name: Build the package
        run: |
          python -m build --sdist --wheel --verbose

      - name: Publish to PyPI
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p ${{ secrets.PYPI_TEST_TOKEN }} --verbose
